name: kedro-action

on:
  push:
    branches:
      - own_workflow

jobs:
  kedro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Kedro
      uses: ./.github/workflows/actions
      with:
        GITHUB_PAT: ${{ secrets.MY_SECRET_TOKEN }} #  required for push to kedro-action branch
        should_lint: false
        should_test: true
        should_build_docs: false
        should_package: false
        should_run: false
        should_viz: false
        verbose: true